### ISSUE TITLE
Scan slices

### ISSUE THREAD

**Issue by roneli** [randallmlough/pgxscan#2]
How do I scan a slice of structs inside a struct?
i.e 
`type SomeStruct struct {
    OtherStruct []OtherStruct
}
type OtherStruct struct {
    A String
}
`
From what I noticed the Struct mapper in scanner.go returns nil on the value hence it doesn't get scanned. I did a query with a join that is 1-n and did json_agg on row_to_json. 
For example:
select * from data cross lateral join (jsonb_agg(jsonb_build_object(...)) from other table where x = y)

i'll try to figure it out by myself on the weekend, if I find a solution i'll post it.

Really like the library btw :)

Edit: Found my issue, it is important that when doing follow scan notation to add tags if the name in embedded struct isn't the same. In my case the json object field names weren't the same as the struct.

**Comment by randallmlough** [comment]
Ah yeah. I'll add some documentation on how to rename struct field names using the `db:""` tag. Thanks for bringing that to my attention.

Additional note – if it's a json column, the same json unmarshalling rules apply as if you were using `json.Unmarshal()`. ie. column names need to match the field names exactly, or the `json:""` tag has to be present.
