### ISSUE TITLE
Scan structs with join tables idea: sentinel/marker row

### ISSUE THREAD

**Issue by pausan** [randallmlough/pgxscan#5]
There are two ways in which scan works right now, using "notate" and "follow". 

**Follow** is really handy and straightforward to use, but unfortunately there are many times where you find names like "id", "created" or "last_updated", etc.. that are present in multiple tables and that creates collission so that "follow" cannot be used.

On the other hand, **notate** comes to the rescue on these cases, but it has the drawback that, since there is no generic way on postgres (nor almost any other database) to automatically prefix everything with dot notation with the name of the table, you need to manually declare all names. If you have a couple of tables, you cannot use "table.*", since if an "id" field exist in both, the column name will be "id" on both, unless you change the select and make it explicit: `table1.id as "table1.id"`

But this is kind of inconvenient since you have to write a lot of code to handle this case... a third possibility would be to use some sort of sentinel row, so it can be used to properly match duplicates and know where to add them. It is similar to **notate** in a way, but with the easy of use of **follow**.

Here is an example:

```
SELECT u.*,
       'Address' as pgx_sentinel, 
       a.*
  FROM users as u,
       addresses as a
WHERE a.user_id = u.id
```

This way, it can resolve duplicates because all columns related to address appear after the sentinel. In fact, you could potentially define N sentinels, using the same column name of **pgx_sentinel** (or whatever you think is good enough), in case you have a more complex join, and the same logic would apply. Resolution will just work. It would be as straighforward as **follow** but with the flexibility of **notate**. The only drawback of this method is that it creates extra bandwidth usage but simplifies a lot.

By the way, thanks a lot for creating and sharing this awesome library.  Let me know your thoughts.

**Comment by randallmlough** [comment]
I'm all for better ways of handling duplicates and less aliasing. It's definitely a pain point I'm aware of (I have experienced it myself), but haven't been able to come up with a good solution yet

**Comment by pausan** [comment]
I'll give a though on aliasing and see if I can come up with some ideas, but I'm afraid is a really hard problem to make it look simple from a user of the library perspective.  It is like the other open ticket there is on the library, my guess is that it is also hard to handle althought I'm not familiarized enough with the library yet, nor with the reflection system of go.

The delimiters solution seems simple to reason about but I'm not sure will cover all cases, nor the performance impact of it, although I believe convenience is more desirable for a feature like this, because performance can be achieved by any of the other two existing methods.

Anyway, I'll try to think and experiment a little bit with go reflection and pgx library and see if I can come up with something.

**Comment by pausan** [comment]
After some time playing with reflection, understanding the library, and having a look at sqlmaper to understand all the magic, I experimented a little bit and found a pragmatic approach that is easy to use from the point of view of the user of the pgxscan library.  It is similar to what I mentioned the other day, but given how the library works, and the way structs are annotated, I think this makes the most sense and looks the most natural (I tried my best given SQL syntax I know of).

In order to allow querying multiple columns at the same time and allow conflicting names being returned, and mapped properly by the library, we need to disambiguate columns, for that reason aliasing with dot notation works really great, but current solution needs the developer to explicitly write down every column and alias. You cannot do "users.*".

To solve this, we can introduce a kind of marker column that can be parsed to prefix following columns with whatever we want, that way, the returned rows can be properly mapped because header names are disambiguated. Let me show an example.

Given the tests/examples in pgxscan, the following query:
```sql
SELECT users.*, address.*
FROM users, address
WHERE users.id = 1 AND address.user_id = address.id
``` 

Will return the following columns:
``` [ "id", "name", "email", "id", "user_id", "line_1", "city"] ```

Which, of course, have "id" duplicated (and user_id which does not belong to Address struct in go code).

The new syntax introduces "notate:" prefix, which given that it contains colon, I don't believe will be conflicting in any existing SQL code. Thus, the query to disambiguate columns could be written as:

```sql
SELECT
   users.*, 
   0 as "notate:address",
   address.*
FROM users, address
WHERE users.id = 1 AND address.user_id = address.id
``` 

And while this will return the following columns:
``` [ "id", "name", "email", "notate:address", "id", "user_id", "line_1", "city"] ```

The internal mapper in pgxscan will map the following columns:
``` [ "id", "name", "email", "address.id", "address.user_id", "address.line_1", "address.city"] ```

The column "notate:address" is just ignored (it gets mapped, but not returned to the struct), whereas "address.user_id" with a new parameter when creating the scanner  MatchAllColumns(false) would also be ignored.

The only downside is that two columns are returned from the server and ignored, but the upside is that the query is kind of clean, plus we use a fairly similar syntax on how struct annotation works in golang for this library.

We could also do things like:
```sql
SELECT
   0 as "notate:user",
   users.*, 
   0 as "notate:address",
   address.*
FROM users, address
WHERE users.id = 1 AND address.user_id = address.id
``` 

Which would map to the following struct columns:
``` [ "user.id", "user.name", "user.email", "address.id", "address.user_id", "address.line_1", "address.city"] ```

I've made the following pull request with this functionality:
https://github.com/randallmlough/pgxscan/pull/7

Without breaking any test or existing behaviour of the library it adds this new capability. Column names are parsed once, with no extra parsing or allocation needed (apart of what the library was doing).

Let me know your thoughts.

**Comment by pausan** [comment]
Well, as an extension to the library, it would be straightforward to create yet another option to list the specific column names the programmer wants to ignore (to have more granular control).

**Comment by randallmlough** [comment]
I'll play with this and the PR associated with it. Truthfully, I'm a little hesitant on the idea of adding dummy columns to the SQL for the sole purpose of the scanning library. IMO that's a little too intrusive and opens the door for a lot of unforeseen problems. 

All that said, I'm revisiting the idea of passing in configuration options when the library is initialized, ie. something like `pgxscan.NewScanner(rows, NotateAlways)` which could potentially solve the problem with some refactoring

**Comment by pausan** [comment]
I totally understand, I thought a lot about it and I see your point. However from the point of view of the user of this package, in certain use cases it reduces a lot the work to list all columns and aliase them. I think that's the benefit of this feature for the library (more below). The good thing is that it is opt-in. Use it if you need it, don't use it if you don't, but it is up to the user of the package.

After spending some time analyzing the problem, thinking in different ways to solve it, I came to the conclusion that the only way to solve it in simple terms required some sort of marker in the SQL, otherwise, as a parameter or otherwise, in goland, you would have to tell the library something like: from column 3 to 8 use "table.xx" as alias, then from column 9 use "othertable.", .... So it makes it harder, whereas embedded in the SQL itself it is easy to recognize and reason about.

The other way to try to solve it from go-land would be to use the existing column names as markers, but here is the problem: say you have three structs with fields (A,B), (B,C) and (A,C), and you have a query returning all three; the only way to tell the mapper where something starts or ends, is to say, on the first B you start using this "table" to notate the fields, on the second A this other table, etc.... and what if the second table introduces A field? Then you have to change go code or it won't be working as expected. Also, there is no guarantee of the column order returned, that's why the only way to support a functionality like the one being discussed is to add some sort of marker in SQL (at least to the best of my knowledge). There is no other way of introducing the markers that does not make things more difficult to reason about or requires more queries to the database. Being a dummy column with a 0 value should reduce performance and bandwidth issues. For queries returning a decent number of rows should work fast enough.

In a way, the beauty of introducing the marker in the SQL itself is that all these issues go away, it becomes very easy to visually reason about it. The drawback is you add a dummy column (no other SQL trick that I could think of, unfortunately). I've been thinking as well about possible side-effects, but I couldn't find any unforeseen future problems, but of course, that does not mean there will not be. In any case, that is why all the functionality is in one place (_GetColumnNames_).

**Summary:**
**This feature provides convenience over performance**. If the user wants performance, then he definitely has to list all items, but if it wants real performance, then I would say the user needs to use pgx directly. From my point of view pgxscan provides convenience over performance compared to pgx itself, this is why I believe this fix makes sense in a package like this one :smile: 

I hope my explanation helps you understand my line of though.

Thanks again for considering it :)

**Comment by randallmlough** [comment]
That's fair. I think this is a good enough solution until a better solution comes about. If you update the PR to fit the current structure I'll happily add it to the library. 

Thanks for documenting the behavior on README as well.

**Comment by pausan** [comment]
Cool. I'll rework the branch and merge changes as soon as I can.

**Comment by randallmlough** [comment]
Merged in the PR and cut a new release. `pgxscan` has now been bumped to `0.3.0`. Thanks a lot for your hard work and time on this!

**Comment by pausan** [comment]
You are welcome! :smile: 

I think I can close this issue now :wink:
